#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/student
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8181
  error:
    include-message: always
    include-binding-errors: always



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentmt
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: ${BASIC_USER:sales}
      password: ${BASIC_PASSWORD:monitoring}

#  hikari:
#    minimum-idle: 5
#    maximum-pool-size: 20
#    idle-timeout: 30000
#    max-lifetime: 2000000
#    connection-timeout: 30000
#    pool-name: HikariAuthPool
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: none
#    show-sql: 'true'
